// <auto-generated />
namespace WebParking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ParkingDB1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ParkingDB1));
        
        string IMigrationMetadata.Id
        {
            get { return "201606231021149_ParkingDB1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
